// <auto-generated />
using System;
using EBL.FIG.Process.Identity.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EBL.FIG.Process.Identity.Infra.Data.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    partial class IdentityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EBL.FIG.Process.Identity.Domain.Entities.ActionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("DATETIME2(7)");

                    b.Property<int>("AppId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("DATETIME2(7)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("INT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Actions");

                    b.HasIndex("TenantId", "AppId", "Id")
                        .IsUnique()
                        .HasDatabaseName("UQ_Actions_Tenant_AppsId_Id");

                    b.HasIndex("TenantId", "AppId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_Actions_Tenant_AppId_Name");

                    b.ToTable("Actions", "dbo");
                });

            modelBuilder.Entity("EBL.FIG.Process.Identity.Domain.Entities.AppEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("DATETIME2(7)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("DATETIME2(7)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Apps");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("UQ_Apps_Tenant_Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_Apps_Tenant_Name");

                    b.ToTable("Apps", "dbo");
                });

            modelBuilder.Entity("EBL.FIG.Process.Identity.Domain.Entities.JobDefinitionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddedBy")
                        .HasColumnType("INT");

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("DATETIME2(7)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("Configuration")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("CronExpression")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR(1000)");

                    b.Property<bool>("ExecuteOnlyOnce")
                        .HasColumnType("BIT");

                    b.Property<string>("HangfireJobId")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSystemJob")
                        .HasColumnType("BIT");

                    b.Property<DateTime?>("LastRegisteredAt")
                        .HasColumnType("DATETIME2(7)");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("INT");

                    b.Property<string>("Method")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("DATETIME2(7)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("INT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<int>("Priority")
                        .HasColumnType("INT");

                    b.Property<string>("Purpose")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR(1000)");

                    b.Property<string>("Queue")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<string>("TimeZoneId")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<int>("TimeoutMinutes")
                        .HasColumnType("INT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR(200)");

                    b.HasKey("Id");

                    b.HasIndex("HangfireJobId")
                        .HasDatabaseName("IX_Services_HangfireJobId")
                        .HasFilter("HangfireJobId IS NOT NULL");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_Job_JobName");

                    b.HasIndex("IsActive", "IsSystemJob")
                        .HasDatabaseName("IX_Services_Active_SYSTEM")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("Category", "IsActive", "IsDeleted")
                        .HasDatabaseName("IX_Services_Category_Active");

                    b.ToTable("JobDefinitions", "dbo");
                });

            modelBuilder.Entity("EBL.FIG.Process.Identity.Domain.Entities.JwtKeyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("AddedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("DATETIME2(7)");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("KeyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KeySize")
                        .HasColumnType("int");

                    b.Property<string>("KeyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastValidatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxTokenLifetimeMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("DATETIME2(7)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("INT");

                    b.Property<DateTime>("NextRotationAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OverlapPeriodDays")
                        .HasColumnType("int");

                    b.Property<string>("PrivateKeyEncrypted")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RotationPolicyDays")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<long>("UsageCount")
                        .HasColumnType("bigint");

                    b.Property<long>("ValidationCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_JwtKeys_Expiration")
                        .HasFilter("IsActive = 1 AND IsDeleted = 0 AND RevokedAt IS NULL");

                    b.HasIndex("KeyId")
                        .IsUnique()
                        .HasDatabaseName("IX_JwtKeys_KeyId_Lookup")
                        .HasFilter("IsDeleted = 0 AND RevokedAt IS NULL");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("KeyId"), new[] { "Algorithm", "PublicKey" });

                    b.HasIndex("NextRotationAt")
                        .HasDatabaseName("IX_JwtKeys_NextRotation")
                        .HasFilter("IsActive = 1 AND IsDeleted = 0 AND RevokedAt IS NULL");

                    b.HasIndex("TenantId");

                    b.HasIndex("IsActive", "IsDeleted")
                        .HasDatabaseName("IX_JwtKeys_IsActive_IsDeleted")
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("JwtKeys", "dbo");
                });

            modelBuilder.Entity("EBL.FIG.Process.Identity.Domain.Entities.PasswordResetTokenEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("DATETIME2(7)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("DATETIME2(7)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("DATETIME2(7)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("INT");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("VARBINARY(64)")
                        .HasColumnName("TokenHash");

                    b.Property<bool>("Used")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(false);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_PasswordResetTokens");

                    b.HasIndex("TenantId", "TokenHash")
                        .IsUnique()
                        .HasDatabaseName("IX_PasswordResetTokens_TenantId_TokenHash");

                    b.HasIndex("UserId", "TenantId");

                    b.HasIndex("TenantId", "UserId", "AddedOn")
                        .HasDatabaseName("IX_PasswordResetTokens_RateLimit");

                    b.ToTable("PasswordResetTokens", "dbo");
                });

            modelBuilder.Entity("EBL.FIG.Process.Identity.Domain.Entities.RefreshTokenEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("DATETIME2(7)");

                    b.Property<int>("AppId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("DATETIME2(7)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("DATETIME2(7)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("INT");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("DATETIME2(7)");

                    b.Property<int?>("RevokedBy")
                        .HasColumnType("INT");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("VARBINARY(64)")
                        .HasColumnName("TokenHash");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_RefreshTokens");

                    b.HasIndex("RevokedBy", "TenantId");

                    b.HasIndex("TenantId", "ExpiresAt")
                        .HasDatabaseName("IX_RefreshTokens_ExpiresAt")
                        .HasFilter("RevokedAt IS NULL");

                    b.HasIndex("TenantId", "UserId")
                        .HasDatabaseName("IX_RefreshTokens_User_Active")
                        .HasFilter("RevokedAt IS NULL");

                    b.HasIndex("UserId", "TenantId");

                    b.HasIndex("TenantId", "AppId", "TokenHash")
                        .IsUnique()
                        .HasDatabaseName("UQ_RefreshTokens");

                    b.ToTable("RefreshTokens", "dbo");
                });

            modelBuilder.Entity("EBL.FIG.Process.Identity.Domain.Entities.ResourceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("DATETIME2(7)");

                    b.Property<int>("AppId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("DATETIME2(7)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("INT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Resources");

                    b.HasIndex("TenantId", "AppId", "Id")
                        .IsUnique()
                        .HasDatabaseName("UQ_Resources_Tenant_AppId_Id");

                    b.HasIndex("TenantId", "AppId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_Resources_Tenant_AppId_Name");

                    b.ToTable("Resources", "dbo");
                });

            modelBuilder.Entity("EBL.FIG.Process.Identity.Domain.Entities.RoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("DATETIME2(7)");

                    b.Property<int>("AppId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("DATETIME2(7)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("INT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Roles");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Roles_Id_Tenant");

                    b.HasIndex("TenantId", "AppId", "Id")
                        .IsUnique()
                        .HasDatabaseName("UQ_Roles_Tenant_AppId_Id");

                    b.HasIndex("TenantId", "AppId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_Roles_Tenant_AppId_Name");

                    b.ToTable("Roles", "dbo");
                });

            modelBuilder.Entity("EBL.FIG.Process.Identity.Domain.Entities.RolePermissionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActionId")
                        .HasColumnType("int");

                    b.Property<int>("AppId")
                        .HasColumnType("int");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_RolePermissions");

                    b.HasIndex("TenantId", "AppId", "ActionId");

                    b.HasIndex("TenantId", "AppId", "ResourceId");

                    b.HasIndex("TenantId", "AppId", "RoleId", "ResourceId", "ActionId")
                        .IsUnique()
                        .HasDatabaseName("IX_RolePermissions_Lookup");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("TenantId", "AppId", "RoleId", "ResourceId", "ActionId"), new[] { "Id" });

                    b.ToTable("RolePermissions", "dbo");
                });

            modelBuilder.Entity("EBL.FIG.Process.Identity.Domain.Entities.TenantEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddedBy")
                        .HasColumnType("INT");

                    b.Property<DateTime>("AddedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIT")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("DATETIME2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("INT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR(1000)");

                    b.Property<string>("Settings")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("UrlImage")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR(500)");

                    b.HasKey("Id")
                        .HasName("PK_Tenants");

                    b.ToTable("Tenants", "dbo");
                });

            modelBuilder.Entity("EBL.FIG.Process.Identity.Domain.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("DATETIME2(7)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastAccessAt")
                        .HasColumnType("DATETIME2");

                    b.Property<string>("LoginIdentifier")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR(500)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("DATETIME2(7)");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("INT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR(150)");

                    b.Property<string>("NormalizedLoginIdentifier")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR(500)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR(500)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("UrlImage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_Users");

                    b.HasAlternateKey("Id", "TenantId")
                        .HasName("UQ_Users_Id_Tenant");

                    b.HasIndex("TenantId", "NormalizedLoginIdentifier")
                        .IsUnique()
                        .HasDatabaseName("UQ_Users_Tenant_NormalizedLoginIdentifier");

                    b.ToTable("Users", "dbo");
                });

            modelBuilder.Entity("EBL.FIG.Process.Identity.Domain.Entities.UserRoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_UserRoles");

                    b.HasIndex("UserId", "TenantId");

                    b.HasIndex("TenantId", "AppId", "RoleId");

                    b.HasIndex("TenantId", "UserId", "AppId")
                        .HasDatabaseName("IX_UserRoles_User_App");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("TenantId", "UserId", "AppId"), new[] { "RoleId" });

                    b.HasIndex("TenantId", "AppId", "UserId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("UQ_UserRoles");

                    b.ToTable("UserRoles", "dbo");
                });

            modelBuilder.Entity("EBL.FIG.Process.Identity.Domain.Entities.ActionEntity", b =>
                {
                    b.HasOne("EBL.FIG.Process.Identity.Domain.Entities.TenantEntity", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Actions_Tenant");

                    b.HasOne("EBL.FIG.Process.Identity.Domain.Entities.AppEntity", "App")
                        .WithMany()
                        .HasForeignKey("TenantId", "AppId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Actions_Apps");

                    b.Navigation("App");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("EBL.FIG.Process.Identity.Domain.Entities.AppEntity", b =>
                {
                    b.HasOne("EBL.FIG.Process.Identity.Domain.Entities.TenantEntity", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Apps_Tenant");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("EBL.FIG.Process.Identity.Domain.Entities.JwtKeyEntity", b =>
                {
                    b.HasOne("EBL.FIG.Process.Identity.Domain.Entities.TenantEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EBL.FIG.Process.Identity.Domain.Entities.PasswordResetTokenEntity", b =>
                {
                    b.HasOne("EBL.FIG.Process.Identity.Domain.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId", "TenantId")
                        .HasPrincipalKey("Id", "TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PasswordResetTokens_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EBL.FIG.Process.Identity.Domain.Entities.RefreshTokenEntity", b =>
                {
                    b.HasOne("EBL.FIG.Process.Identity.Domain.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("RevokedBy", "TenantId")
                        .HasPrincipalKey("Id", "TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_RefreshTokens_RevokedBy");

                    b.HasOne("EBL.FIG.Process.Identity.Domain.Entities.AppEntity", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "AppId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RefreshTokens_Apps");

                    b.HasOne("EBL.FIG.Process.Identity.Domain.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId", "TenantId")
                        .HasPrincipalKey("Id", "TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RefreshTokens_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EBL.FIG.Process.Identity.Domain.Entities.ResourceEntity", b =>
                {
                    b.HasOne("EBL.FIG.Process.Identity.Domain.Entities.TenantEntity", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Resources_Tenant");

                    b.HasOne("EBL.FIG.Process.Identity.Domain.Entities.AppEntity", "App")
                        .WithMany()
                        .HasForeignKey("TenantId", "AppId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Resources_Apps");

                    b.Navigation("App");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("EBL.FIG.Process.Identity.Domain.Entities.RoleEntity", b =>
                {
                    b.HasOne("EBL.FIG.Process.Identity.Domain.Entities.TenantEntity", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Roles_Tenant");

                    b.HasOne("EBL.FIG.Process.Identity.Domain.Entities.AppEntity", "App")
                        .WithMany()
                        .HasForeignKey("TenantId", "AppId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Roles_Apps");

                    b.Navigation("App");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("EBL.FIG.Process.Identity.Domain.Entities.RolePermissionEntity", b =>
                {
                    b.HasOne("EBL.FIG.Process.Identity.Domain.Entities.TenantEntity", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RolePermissions_Tenant");

                    b.HasOne("EBL.FIG.Process.Identity.Domain.Entities.AppEntity", "App")
                        .WithMany()
                        .HasForeignKey("TenantId", "AppId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RolePermissions_Apps");

                    b.HasOne("EBL.FIG.Process.Identity.Domain.Entities.ActionEntity", "Action")
                        .WithMany("RolePermissions")
                        .HasForeignKey("TenantId", "AppId", "ActionId")
                        .HasPrincipalKey("TenantId", "AppId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RolePermissions_Action");

                    b.HasOne("EBL.FIG.Process.Identity.Domain.Entities.ResourceEntity", "Resource")
                        .WithMany("RolePermissions")
                        .HasForeignKey("TenantId", "AppId", "ResourceId")
                        .HasPrincipalKey("TenantId", "AppId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RolePermissions_Resource");

                    b.HasOne("EBL.FIG.Process.Identity.Domain.Entities.RoleEntity", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("TenantId", "AppId", "RoleId")
                        .HasPrincipalKey("TenantId", "AppId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RolePermissions_Role");

                    b.Navigation("Action");

                    b.Navigation("App");

                    b.Navigation("Resource");

                    b.Navigation("Role");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("EBL.FIG.Process.Identity.Domain.Entities.UserEntity", b =>
                {
                    b.HasOne("EBL.FIG.Process.Identity.Domain.Entities.TenantEntity", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Users_Tenant");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("EBL.FIG.Process.Identity.Domain.Entities.UserRoleEntity", b =>
                {
                    b.HasOne("EBL.FIG.Process.Identity.Domain.Entities.TenantEntity", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UserRoles_Tenant");

                    b.HasOne("EBL.FIG.Process.Identity.Domain.Entities.AppEntity", "App")
                        .WithMany()
                        .HasForeignKey("TenantId", "AppId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UserRoles_Apps");

                    b.HasOne("EBL.FIG.Process.Identity.Domain.Entities.UserEntity", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId", "TenantId")
                        .HasPrincipalKey("Id", "TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UserRoles_User");

                    b.HasOne("EBL.FIG.Process.Identity.Domain.Entities.RoleEntity", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("TenantId", "AppId", "RoleId")
                        .HasPrincipalKey("TenantId", "AppId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_UserRoles_Role");

                    b.Navigation("App");

                    b.Navigation("Role");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EBL.FIG.Process.Identity.Domain.Entities.ActionEntity", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("EBL.FIG.Process.Identity.Domain.Entities.ResourceEntity", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("EBL.FIG.Process.Identity.Domain.Entities.RoleEntity", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("EBL.FIG.Process.Identity.Domain.Entities.TenantEntity", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("EBL.FIG.Process.Identity.Domain.Entities.UserEntity", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
